iqkv :
  info :
    description : '@project.description@'
    relative-path : ${SERVER_SERVLET_CONTEXT_PATH:/}
    version : '@project.version@'

git :
  build_time : '@git.build.time@'
  commit : '@git.commit.id.abbrev@'
info :
  app :
    build_time : ${git.build_time}
    description : '@project.description@'
    git_commit : ${git.commit}
    name : '@project.name@'
    version : '@project.version@'

logging :
  pattern :
    level : '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level :
    ROOT : ${LOGGING_LEVEL_ROOT:INFO}

management :
  health :
    livenessstate :
      enabled : true
    readinessstate :
      enabled : true
  endpoint :
    health :
      enabled : true
      show-details : always
      probes :
        enabled : true
    info :
      enabled : true
    env :
      show-values : always
      enabled : true
    prometheus :
      enabled : true
  endpoints :
    enabled-by-default : false
    web :
      exposure :
        include : health, metrics, prometheus, info, env, openapi, swagger-ui
  info :
    env :
      enabled : true
    java :
      enabled : true
    os :
      enabled : true

  server :
    port : ${MANAGEMENT_SERVER_PORT:8080}
    add-application-context-header : true

  metrics :
    tags :
      application : ${spring.application.name}
      profiles : ${spring.profiles.active}
    distribution :
      percentiles-histogram :
        http :
          server :
            requests : true
  tracing :
    sampling :
      probability : 1.0
    enabled : true
    propagation :
      type : w3c
  prometheus :
    metrics :
      export :
        step : 20s
        enabled : true
  zipkin :
    tracing :
      endpoint : ${TEMPO_URL:http://localhost:9411/api/v2/spans}

server :
  port : ${SERVER_PORT:8080}
  shutdown : graceful
  forward-headers-strategy : framework
  tomcat :
    redirect-context-root : false
spring :
  application :
    name : quickstart-mvc-rest-hello-world
  devtools :
    add-properties : false
    livereload :
      enabled : false
    restart :
      enabled : false
  jackson :
    default-property-inclusion : NON_NULL
  lifecycle :
    timeout-per-shutdown-phase : ${TIMEOUT_PER_SHUTDOWN:20s}

springdoc :
  show-actuator : false
